### ISSUE TITLE
Reload from disk after mob start

### ISSUE THREAD

**Issue by jochenchrist** [remotemobprogramming/intellij-mob#5]
Feature-Request:

Mob next / Changing the branch may cause new files to appear.

Trigger "Reload from disk" when _mob start_ was executed.

**Comment by nowsprinting** [comment]
@jochenchrist san, Thanks your report!

I fix refresh project files after start/next/done/reset actions.

Can you check your problem is gone?
Please download [build#19](https://github.com/remotemobprogramming/intellij-mob/actions/runs/103102840) artifact, unzip, and install "intellij-mob-516f91c.zip".
